spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:forum
    username: ruan
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
jwt:
  secret: minha_senha_super_hiper_mega_ultra_secreta
